### ISSUE TITLE
Squares are off by 1px

### ISSUE THREAD

**Issue by freechessclub-dev** [ornicar/chessground#201]
Since v8.0.0, I've been noticing selection/highlighting etc. be off by 1 pixel (see below). I bisected it down to #191. The issue is observed on multiple devices with at least Edge and Chrome.

![Capture](https://user-images.githubusercontent.com/79025846/128474767-e908af2e-3cfe-467c-9ff6-4b76efd79971.PNG)

Any pointers on how to fix it?

**Comment by niklasf** [comment]
Hi. Do you see the same issue with the boards on lichess.org (like https://lichess.org/analysis)? If not it's probably due to slight changes to CSS and markup from the same commit (https://github.com/ornicar/chessground/pull/191/files#diff-637295579819c44264e189e269f2a73ecf54988667b4187b5495ee7760f6592a).
