### ISSUE TITLE
en passant capture isn't handled correctly

### ISSUE THREAD

**Issue by StillLearnin** [ornicar/chessground#23]
When capturing an enemy pawn that has passed your pawn by moving two places, clicking your pawn shows that you can either move straight ahead or capture the enemy pawn.

![image](https://cloud.githubusercontent.com/assets/2912263/12054987/9d022ce8-aef6-11e5-9741-21d3509f4803.png)

After capturing the enemy pawn, the enemy pawn remains on the board but can't be moved.

![image](https://cloud.githubusercontent.com/assets/2912263/12055001/cf113896-aef6-11e5-9b0a-cf873eee963a.png)

**Comment by ornicar** [comment]
as the readme states, there's no chess logic inside chessground. I.E. chessground does not know the rules of chess. They have to be provided by a third party.

**Comment by clementvp** [comment]
Hey, i know this issue is closed since a long time, but for the people who use chessJs as a third party this is a simple and dirty workaround:
use the .move() method of chessJS.
This method  return a object with 'flags' property.
If the flag is : e  that's a en passant standard capture.
If you watch this flag, just load Chessground with the correct fen who is returned by ChessJS under the .fen() method.
In my class called Engine:
```
var move = this.chess.move({ from: orig, to: dest, promotion: 'q' })
if (move.flags === 'e') {
        this.cg.set({ fen: this.chess.fen() })
 }
```
That's better than working with the .setPieces() method of Chessground.
